#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: vsa-monitoring | monasca monitoring | Copy vsa checks plugin to {{ monasca_agent_check_plugin_dir }}
  copy:
    src: check/vsa.py
    dest: "{{ monasca_agent_check_plugin_dir }}"

- name: vsa-monitoring | monasca monitoring | Copy vsa detection plugin to {{ monasca_agent_detection_plugin_dir }}
  copy:
    src: detection/vsa.py
    dest: "{{ monasca_agent_detection_plugin_dir }}"

- name: vsa-monitoring | monasca monitoring | Run monasca agent vsa detection plugin
  monasca_agent_plugin:
    name="Vsa"

# Variable keystone_url is defined in the dependent monasca_agent role
- name: vsa-monitoring  | monasca alarms | Create monasca alarm definitions for vsa
  run_once: true
  monasca_alarm_definition:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    severity: "{{ item.severity }}"
    expression: "{{ item.expression }}"
    match_by: "{{ item.match_by }}"
    keystone_url: "{{ keystone_url }}"
    keystone_user: "{{ keystone_user }}"
    keystone_password: "{{ keystone_password }}"
    keystone_project: "{{ keystone_project }}"
    monasca_api_url: "{{ monasca_alarm_definition_api_url }}"
  with_items:
    - { name: "VSA VM Status",
        description: "Alarms if VSA VM is down",
        severity: "HIGH",
        expression: "vsa_vm_status > 0",
        match_by: ["hostname"]}
    - { name: "VSA VM Network Status",
        description: "Alarms if VSA VM Network is down",
        severity: "HIGH",
        expression: "vsa_vm_net_status > 0",
        match_by: ["hostname"]}
