#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Set the fact for restart based on hlm_notify
- name: KEY-API | start | Set fact to start based on hlm_notify_fact
  set_fact:
    keystone_restart_required : True
  when: hlm_notify_keystone_change is defined and hlm_notify_keystone_change.changed

- name: KEY-API | start | Check if keystone site enabled
  become: yes
  stat:
    path: /etc/apache2/sites-enabled/keystone-modwsgi.conf
  register: keystone_site_file

# This is for the case stop after start 
- name: KEY-API | start | Set fact to start if it is disabled 
  set_fact: 
    keystone_restart_required : True
  when: not keystone_site_file.stat.exists

- name:  KEY-API | start | Enable keystone site
  command: a2ensite keystone-modwsgi
  tags:
    - keystone

- include: "{{ playbook_dir }}/roles/FND-AP2/tasks/start_reload.yml"
  vars:
    apache_reload_requested: False
    apache_restart_requested: "{{ keystone_restart_required }}"

- name: KEY-API | start | Restart shibd
  service:
    name: shibd
    state: restarted
  tags:
    - keystone

- name: KEY-API | start | Wait for keystone to become active
  wait_for:
    host: "{{ host.vars.my_network_name }}"
    port: "{{ item }}"
    state: "started"
    timeout: 60
  with_items:
   - "{{ keystone_admin_vip_port }}"
   - "{{ keystone_public_vip_port }}"
  tags:
    - keystone

- name: KEY-API | start | Make sure keystone is up and responding
  uri:
     url: "{{ keystone_internal_endpoint }}"
     status_code: 300
     timeout: 20
  register: keystone_version_status
  until: keystone_version_status.status is defined and keystone_version_status.status == 300
  delay: 10
  retries: 3
  run_once: true
  tags:
    - keystone
