#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- include_vars:
    ../../CND-VOL/vars/cinder_vol_run_location.yml

- name: Cinder Monitor | monasca_alarms | set cinder volume should not be running monitor facts
  set_fact: "{{ item.name }}_running_check='cinderlm.cinder.cinder_services{component={{ item.daemon }},hostname={{ inventory_hostname }}} > {{ process_count_notrunning_upper_bound }}'"
  when: (_cinder_volume_running_here == "False")
  with_items:
    - daemon: "cinder-volume"
      name: "cinder_volume"
    - daemon: "cinder-backup"
      name: "cinder_backup"

- name: Cinder Monitor | monasca_alarms | set cinder volume should be running monitor facts
  set_fact: "{{ item.name }}_running_check='cinderlm.cinder.cinder_services{component={{ item.daemon }},hostname={{ inventory_hostname }}} < {{ process_count_running_lower_bound }}'"
  when: (_cinder_volume_running_here == "True")
  with_items:
    - daemon: "cinder-volume"
      name: "cinder_volume"
    - daemon: "cinder-backup"
      name: "cinder_backup"

- name: Cinder Monitor | monasca-alarms | Setup default email notification method
  monasca_notification_method:
    name: "Default Email"
    type: 'EMAIL'
    address: "root@localhost"
    keystone_url: "{{ cinder_keystone.admin_url }}"
    keystone_user: "{{ KEY_API.vars.keystone_admin_user }}"
    keystone_password: "{{ KEY_API.vars.keystone_admin_pwd }}"
    keystone_project: "{{ KEY_API.vars.keystone_admin_tenant }}"
    monasca_api_url: "{{ monasca_alarm_definition_api_url }}"
    overwrite: false
  register: cinder_default_notification
  run_once: true

- name: Cinder Monitor | monasca_alarms | backup/volume running alarm definition
  monasca_alarm_definition:
    name: "Cinder {{ item.name }} running {{ inventory_hostname }} check"
    description: "Alarms if the cinder {{ item.name }} service is not appropriately set up."
    severity: "HIGH"
    expression: "{{ item.expression }}"
    match_by: ["hostname"]
    keystone_url: "{{ cinder_keystone.admin_url }}"
    keystone_user: "{{ KEY_API.vars.keystone_admin_user }}"
    keystone_password: "{{ KEY_API.vars.keystone_admin_pwd }}"
    keystone_project: "{{ KEY_API.vars.keystone_admin_tenant }}"
    monasca_api_url: "{{ monasca_alarm_definition_api_url }}"
    state: "{{ cinder_volume_monitor_state }}"
    ok_actions:
      - "{{ cinder_default_notification.notification_method_id }}"
    undetermined_actions:
      - "{{ cinder_default_notification.notification_method_id }}"
    alarm_actions:
      - "{{ cinder_default_notification.notification_method_id }}"
  with_items:
    - expression: "{{ cinder_volume_running_check }}"
      name: "volume"
    - expression: "{{ cinder_backup_running_check }}"
      name: "backup"

# This alarm definition is redundant for HOS 3.0 and is being marked absent
- name: Cinder Monitor | monasca_alarms | Create monasca alarm definitions
  run_once: true
  monasca_alarm_definition:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    severity: "{{ item.severity }}"
    expression: "{{ item.expression }}"
    match_by: "{{ item.match_by }}"
    keystone_url: "{{ cinder_keystone.admin_url }}"
    keystone_user: "{{ KEY_API.vars.keystone_admin_user }}"
    keystone_password: "{{ KEY_API.vars.keystone_admin_pwd }}"
    keystone_project: "{{ KEY_API.vars.keystone_admin_tenant }}"
    monasca_api_url: "{{ monasca_alarm_definition_api_url }}"
    state: "absent"
  with_items:
    - { name: "Cinderlm diagnostics monitor",
        description: "Alarms if cinder monitoring cannot execute a task",
        severity: "HIGH",
        expression: "cinderlm.cinderlm_check > 0",
        match_by: ["hostname"]}

# Create an alarm for local disks' status
# Needs to be done once for the entire system
- name: Cinder Monitor | monasca_alarms | HP local disks alarm definition
  run_once: true
  monasca_alarm_definition:
    name: "Storage {{ item.name }} check"
    description: "Alarms if the {{ item.name }} metric is not OK."
    severity: "HIGH"
    expression: "{{ item.expression }}"
    match_by: ["hostname"]
    keystone_url: "{{ cinder_keystone.admin_url }}"
    keystone_user: "{{ KEY_API.vars.keystone_admin_user }}"
    keystone_password: "{{ KEY_API.vars.keystone_admin_pwd }}"
    keystone_project: "{{ KEY_API.vars.keystone_admin_tenant }}"
    monasca_api_url: "{{ monasca_alarm_definition_api_url }}"
    state: present
    ok_actions:
      - "{{ cinder_default_notification.notification_method_id }}"
    undetermined_actions:
      - "{{ cinder_default_notification.notification_method_id }}"
    alarm_actions:
      - "{{ cinder_default_notification.notification_method_id }}"
  with_items:
    # Note > 0 also picks up a warning
    # - its legitimate to alarm for a drive warning
    - expression: "cinderlm.hp_hardware.hpssacli.logical_drive{component=logical_drive,service=block-storage,sub_component=lun_status} > 0"
      name: "faulty lun"
    - expression: "cinderlm.hp_hardware.hpssacli.physical_drive{component=physical_drive,service=block-storage} > 0"
      name: "faulty drive"

# NOTE: Construct URL the same way as HOS V2.1 to avoid upgrade issues
- name: Cinder Monitor | monasca_alarms | Construct VIP URL for Active check
  set_fact:
    _cinder_vip_url: "{{ CND_API | item ('advertises.vips.private[0].protocol') }}://{{ CND_API | item ('advertises.vips.private[0].host') }}:{{ CND_API | item ('advertises.vips.private[0].port') }}/"

# NOTE: Admin endpoint may not be accessible from internal nodes in the long term.
- name: Cinder Monitor | monasca_alarms | Setup Active check against Cinder VIP
  monasca_agent_plugin:
    name="httpcheck"
    args="use_keystone=False match_pattern=.*versions.*CURRENT.* url={{ _cinder_vip_url }} dimensions=service:block-storage,component:cinder-api,vip:internal"
