#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Top-level HLM Keystone credentials change playbook
---
- include: hlm-ping-test.yml

# Just in case MySQL passwords were changed in addition to Keystone passwords
- include: percona-reconfigure.yml

- include: keystone-reconfigure-credentials.yml

- include: barbican-reconfigure-credentials-change.yml
- include: monasca-reconfigure-credentials-change.yml
- include: ops-console-reconfigure-credentials-change.yml
- include: swift-reconfigure-credentials-change.yml
- include: glance-reconfigure-credentials-change.yml
- include: neutron-reconfigure-credentials-change.yml
- include: ironic-reconfigure-credentials-change.yml
- include: _nova-reconfigure-credentials-change.yml
- include: cinder-reconfigure-credentials-change.yml
- include: designate-reconfigure-credentials-change.yml
- include: eon-reconfigure-credentials-change.yml
- include: heat-reconfigure-credentials-change.yml
- include: kronos-reconfigure.yml
- include: ceilometer-reconfigure-credentials-change.yml
- include: freezer-reconfigure-credentials-change.yml
- include: octavia-reconfigure-credentials-change.yml
