#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Top-level HLM deploy playbook
---
- include: hlm-ping-test.yml

# Regather facts on all hosts in case of configuration changes that haven't
# been reflected in the fact cache
- hosts: all
  gather_facts: False
  max_fail_percentage: 0
  tasks:
    - action: setup

- include: sosreport-deploy.yml
- include: upgrade-bootstrap.yml

# HLM-1259: when disabling the monasca part of the deployment,
# edit ~/.ansible.cfg and change the [default] / library setting
# as outlined in that file.
- include: monasca-agent-deploy.yml

- include: tls-deploy.yml
- include: clients-deploy.yml
- include: percona-deploy.yml
- include: rabbitmq-deploy.yml
- include: FND-CLU-deploy.yml
- include: FND-AP2-deploy.yml
- include: memcached-deploy.yml
- include: keystone-deploy.yml
- include: barbican-deploy.yml
- include: zookeeper-deploy.yml
- include: monasca-deploy.yml
- include: hlm-ux-services-deploy.yml
# ops console depends on kafka, installed by monasca
- include: ops-console-deploy.yml
- include: swift-deploy.yml
- include: glance-deploy.yml
- include: neutron-deploy.yml
- include: ironic-deploy.yml
- include: vsa-deploy.yml
- include: cmc-deploy.yml
- include: nova-deploy.yml
- include: cinder-deploy.yml
- include: octavia-deploy.yml
- include: designate-deploy.yml
- include: powerdns-deploy.yml
- include: bind-deploy.yml
- include: eon-deploy.yml
- include: heat-deploy.yml
- include: horizon-deploy.yml
- include: logging-deploy.yml
- include: ceilometer-deploy.yml
- include: ceph-deploy.yml
- include: freezer-deploy.yml
- include: tempest-deploy.yml
- include: hos-extra-deploy.yml
