#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Top-level HLM reconfigure playbook
---
- include: hlm-ping-test.yml

# Regather facts on all hosts in case of configuration changes that haven't
# been reflected in the fact cache
- hosts: all
  gather_facts: False
  max_fail_percentage: 0
  tasks:
    - action: setup

- include: network_interface-reconfigure.yml
- include: osconfig-iptables-reconfigure.yml
- include: tls-reconfigure.yml
- include: monasca-agent-reconfigure.yml
- include: percona-reconfigure.yml
- include: rabbitmq-reconfigure.yml
- include: FND-CLU-reconfigure.yml
- include: FND-AP2-reconfigure.yml
- include: memcached-reconfigure.yml
- include: keystone-reconfigure.yml
- include: barbican-reconfigure.yml
- include: zookeeper-reconfigure.yml
- include: monasca-reconfigure.yml
- include: ops-console-reconfigure.yml
- include: swift-reconfigure.yml
- include: glance-reconfigure.yml
- include: neutron-reconfigure.yml
- include: ironic-reconfigure.yml
- include: nova-reconfigure.yml
- include: cinder-reconfigure.yml
- include: octavia-reconfigure.yml
- include: designate-reconfigure.yml
- include: powerdns-reconfigure.yml
- include: bind-reconfigure.yml
- include: eon-reconfigure.yml
- include: heat-reconfigure.yml
- include: horizon-reconfigure.yml
- include: kronos-reconfigure.yml
- include: ceilometer-reconfigure.yml
- include: ceilometer-pipeline-reconfigure.yml
- include: ceph-reconfigure.yml
- include: vsa-reconfigure.yml
- include: freezer-reconfigure.yml
