#
# (c) Copyright 2015,2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- hosts: "NEU-*;!NEU-OVSVAPP"
  sudo: yes
  roles:
  - neutron-common

  tasks:
  - include: roles/neutron-common/tasks/install.yml
  - include: roles/neutron-common/tasks/configure.yml
  - include: roles/neutron-common/tasks/start.yml

- hosts: NEU-OVSVAPP
  sudo: yes
  serial: 3
  roles:
  - neutron-common

  tasks:
  - include: roles/neutron-common/tasks/install.yml
  - include: roles/neutron-common/tasks/configure.yml
  - include: roles/neutron-common/tasks/start.yml

- hosts: NEU-SVR
  sudo: yes
  roles:
  - neutron-post-configure
  tasks:
  - include: roles/neutron-post-configure/tasks/db_configure.yml

- hosts: KEY-CLI
  sudo: yes
  roles:
  - neutron-post-configure
  tasks:
  - include: roles/neutron-post-configure/tasks/keystone_conf.yml
    ansible_python_interpreter: "{{ KEY_CLI.vars.keystone_client_python_interpreter }}"
    when: ( 'NEU_SVR' in verb_hosts ) and ( ( groups[verb_hosts.NEU_SVR] | length ) > 0 )

- hosts: NEU-SVR
  sudo: yes
  roles:
  - neutron-common
  - neutron-server

  tasks:
  - include: roles/neutron-server/tasks/configure.yml
  - include: roles/neutron-server/tasks/start.yml

- hosts: NEU-OVS
  sudo: yes
  roles:
  - neutron-common
  - neutron-openvswitch-agent

  tasks:
  - include: roles/neutron-openvswitch-agent/tasks/install.yml
  - include: roles/neutron-openvswitch-agent/tasks/configure.yml
  - include: roles/neutron-openvswitch-agent/tasks/start.yml

- hosts: NEU-OVSVAPP
  sudo: yes
  serial: 3
  roles:
  - neutron-common
  - neutron-ovsvapp-agent

  tasks:
  - include: roles/neutron-ovsvapp-agent/tasks/install.yml
  - include: roles/neutron-ovsvapp-agent/tasks/configure.yml
  - include: roles/neutron-ovsvapp-agent/tasks/start.yml

- hosts: NEU-DHCP
  sudo: yes
  roles:
  - neutron-common
  - neutron-dhcp-agent

  tasks:
  - include: roles/neutron-dhcp-agent/tasks/install.yml

- hosts: NEU-DHCP
  sudo: yes
  roles:
  - neutron-common
  - neutron-dhcp-agent

  tasks:
  - include: roles/neutron-dhcp-agent/tasks/configure.yml
  - include: roles/neutron-dhcp-agent/tasks/start.yml

- hosts: NEU-MDA
  sudo: yes
  roles:
  - neutron-common
  - neutron-metadata-agent

  tasks:
  - include: roles/neutron-metadata-agent/tasks/configure.yml
  - include: roles/neutron-metadata-agent/tasks/start.yml

- hosts: NEU-L3A
  sudo: yes
  roles:
  - neutron-common
  - neutron-l3-agent

  tasks:
  - include: roles/neutron-l3-agent/tasks/install.yml
  - include: roles/neutron-l3-agent/tasks/configure.yml
  - include: roles/neutron-l3-agent/tasks/start.yml

- hosts: NEU-VPNA
  sudo: yes
  roles:
  - neutron-common
  - neutron-vpn-agent

  tasks:
  - include: roles/neutron-vpn-agent/tasks/install.yml
  - include: roles/neutron-vpn-agent/tasks/configure.yml
  - include: roles/neutron-vpn-agent/tasks/start.yml

- hosts: NEU-LBAV2
  sudo: yes
  roles:
  - neutron-common
  - neutron-lbaasv2-agent

  tasks:
  - include: roles/neutron-lbaasv2-agent/tasks/install.yml
  - include: roles/neutron-lbaasv2-agent/tasks/configure.yml
  - include: roles/neutron-lbaasv2-agent/tasks/start.yml

- hosts: NEU-LBAV1
  sudo: yes
  roles:
  - neutron-common
  - neutron-lbaas-agent

  tasks:
  - include: roles/neutron-lbaas-agent/tasks/install.yml
  - include: roles/neutron-lbaas-agent/tasks/configure.yml
  - include: roles/neutron-lbaas-agent/tasks/start.yml

- hosts: NEU-L2GWA
  sudo: yes
  roles:
  - neutron-common
  - neutron-l2gateway-agent

  tasks:
  - include: roles/neutron-l2gateway-agent/tasks/install.yml
  - include: roles/neutron-l2gateway-agent/tasks/configure.yml
  - include: roles/neutron-l2gateway-agent/tasks/start.yml

- hosts: NEU-IFBLXA
  sudo: yes
  roles:
  - neutron-common
  - neutron-infoblox-ipam-agt
  tasks:
  - include: roles/neutron-infoblox-ipam-agt/tasks/install.yml
  - include: roles/neutron-infoblox-ipam-agt/tasks/configure.yml
  - include: roles/neutron-infoblox-ipam-agt/tasks/start.yml

- hosts: NEU-SVR[0]
  sudo: yes
  roles:
  - neutron-common
  tasks:
  - include: roles/neutron-common/tasks/provider_net_create.yml

# after everything is running, turn on monitoring
- hosts: NEU-DHCP:NEU-L3A:NEU-LBAV*:NEU-MDA:NEU-OVS:NEU-SVR:NEU-VPNA:NEU-L2GWA:NEU-IFBLXA
  sudo: yes
  roles:
  - neutron-common
  - { role: monasca-agent, run_mode: Use }

  tasks:
  - include: roles/neutron-common/tasks/setup_monasca_service_plugin.yml

- hosts: NEU-OVSVAPP
  sudo: yes
  roles:
  - neutron-common

  tasks:
  - include: roles/neutron-common/tasks/setup_ovsvapp_monasca_service_plugin.yml

# set up active check of neutron api via admin vip
- hosts: MON-API
  sudo: yes
  roles:
  - neutron-common
  - { role: monasca-agent, run_mode: Use }

  tasks:
  - include: roles/neutron-common/tasks/add_adminVIP_monasca_checks.yml
    when: ( 'NEU_SVR' in verb_hosts ) and ( ( groups[verb_hosts.NEU_SVR] | length ) > 0 )
