#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- include: _nova-install.yml
- include: _nova-configure.yml
- include: _nova-post-configure.yml
- include: nova-start.yml

# we create a new alarm definition for monitoring processes bounds for nova-api.
# The definition of a new alarm needs to be done just once.
- hosts: NOV-API:NOV-CAU:NOV-CMP:NOV-CND:NOV-SCH:NOV-VNC:&MON-AGN
  no_log: True
  roles:
    - role: nova-monasca
  tasks:
    - include: roles/nova-monasca/tasks/process_bounds_alarm.yml
    - include: roles/nova-monasca/tasks/heartbeat_alarm.yml
