#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- hosts: FND-RMQ
  max_fail_percentage: 0
  roles:
    - rabbitmq
    - hlm-upgrade-tools
  tasks:
    # Sets-up 'check-upgraded-pkgs' value.
    - include: roles/hlm-upgrade-tools/tasks/pkg-query.yml
    # based on the result of 'check-upgraded-pkgs'
    # - hlm_notify_rabbitmq_major_upgrade.changed may be set here to determine
    # which upgrade is run below.
    - include: roles/rabbitmq/tasks/check-upgraded-pkgs.yml
    - include: roles/rabbitmq/tasks/configure.yml
    # Check whether the user has updated the list of RabbitMQ plugins
    - include: roles/rabbitmq/tasks/check-plugins.yml


# Update the users and Monasca agent for RabbitMQ.
- include: rabbitmq-configure-users.yml

# RabbitMQ 3.4.3-3.6.0 workaround rule.
- hosts: FND-RMQ
  gather_facts: no
  max_fail_percentage: 0
  roles:
    - iptables
    - rabbitmq
  tasks:
    - include: roles/rabbitmq/tasks/workaround.yml
      when: hlm_notify_rabbitmq_restart_required.changed or
            hlm_notify_rabbitmq_reset_required.changed

    # Stop messages entering a node by blocking the 'tcp_listener' ports. Need
    # to make the cluster go silent to reduce the likelihood of getting an
    # Erlang Mnesia held lock (OTP-13284).
    - include: roles/iptables/tasks/iptables-add.yml
      vars:
        iptables_chain: "{{ rabbitmq_iptables_chain }}"
        iptables_ip_port: "{{ rabbitmq_cp.bind_addresses }}"
      when: hlm_notify_rabbitmq_workaround_required.changed

# Only one of these will operate depending on the state of
# hlm_notify_rabbitmq_major_upgrade.changed set during check-upgraded-pkgs
# above.
- include: _rabbitmq-minor-upgrade.yml
- include: _rabbitmq-major-upgrade.yml
