#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include_vars:
    existing_master_key.yml

- name: KEYMGR-API | configure_master_key | Print existing master key values
  debug: msg="barbican_simple_crypto_master_key = {{ barbican_simple_crypto_master_key }}, barbican_customer_master_key = {{ barbican_customer_master_key }}"
  when: barbican_debug is defined
  tags:
    - barbican

- name: KEYMGR-API | configure_master_key | Use customer master key or default one if no existing master key there
  set_fact:
    barbican_simple_crypto_master_key: "{{ barbican_customer_master_key | default(barbican_default_master_key, true) }}"
    barbican_set_master_key_first_time: True
  when: barbican_secretstore_plugins == "store_crypto" and not barbican_simple_crypto_master_key
  tags:
    - barbican

- name: KEYMGR-API | configure_master_key | Write existing master key to localhost file
  delegate_to: 127.0.0.1
  copy:
    content: '---\nbarbican_simple_crypto_master_key: {{ barbican_simple_crypto_master_key }}'
    dest: ./roles/KEYMGR-API/vars/existing_master_key.yml
  when: barbican_simple_crypto_master_key and barbican_secretstore_plugins == "store_crypto" and barbican_set_master_key_first_time|default(False)
  tags:
    - barbican