#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# runs on the deployer and is used to configure or not the apt repo
---
- name: osconfig | check-for-apt-repo | Checking for apt-repo
  delegate_to: localhost
  stat:
    path: "{{ hlinux_apt_repo_dir }}/dists"
  register: _apt_repo_stat_result

- set_fact:
    deployer_apt_repo_present: "{{ _apt_repo_stat_result.stat.exists | bool }}"
