#
# Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---

- name: osconfig | kdump setup | kernel parameters
  become: yes
  lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX="" line=GRUB_CMDLINE_LINUX=\"crashkernel=384M-2G:64M,2G-:256M\"
  register: grub_mod

- name: osconfig | kdump setup | setup_kdump through apt
  become: yes
  apt:
    pkg: kdump-tools
    force: yes
  when: ansible_os_family == 'Debian'

- name: osconfig | kdump setup | setup_kdump through yum
  become: yes
  yum:
    pkg: kexec-tools
  when: ansible_os_family == 'RedHat'

- name: osconfig | kdump setup | configure kdump settings
  become: yes
  copy:
    src: kdump_config
    dest: /etc/default/kdump-tools
  register: kdump_mod
  when: ansible_os_family == 'Debian'

- name: osconfig | kdump setup | restart kdump-tools
  become: yes
  service:
     name: kdump-tools
     state: restarted
  when: kdump_mod.changed and ansible_os_family == 'Debian'

- name: osconfig | kdump setup | update-grub
  become: yes
  command: /usr/sbin/update-grub
  when: grub_mod.changed and ansible_os_family == 'Debian'

- name: osconfig | kdump setup | update-grub RedHat
  become: yes
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub_mod.changed and ansible_os_family == 'RedHat'

- name: osconfig | kdump setup | restart kdump RedHat
  become: yes
  service:
     name: kdump
     state: restarted
  when: ansible_os_family == 'RedHat'
