#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

- name: FND-MDB | configure | Remove lost+found if it exists
  file:
    path: "{{ mysql_datadir }}/lost+found"
    state: absent

- name: FND-MDB | configure | Copy my.cnf
  template:
    src: etc/mysql/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: mysql
    group: mysql
    mode: 0600
  register: hlm_notify_mysql_restart_required

- name: FND-MDB | configure | Check initialised
  stat:
    path: "{{ mysql_initialised }}"
  register: checkinitialise

- name: FND-MDB | configure | Purge invalid InnoDB logfiles
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql/ib_logfile0
    - /var/lib/mysql/ib_logfile1
  when: checkinitialise.stat.exists == False

- name:  FND-MDB | configure | Check initialised anywhere else also
  stat:
      path: "{{ mysql_initialised }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['FND-MDB'] }}"
  register: mysqlhere
  run_once: true

- set_fact:
    mysql_bootstrapped: true
  when:  " {{ item.stat.exists }}  == True "
  with_items:   mysqlhere.results
  run_once: true

- include: bootstrap.yml
  when: checkinitialise.stat.exists == False

- name: FND-MDB | configure | Copy logrotate file
  template:
    src: etc/logrotate.d/mysql.j2
    dest: /etc/logrotate.d/mysql
    owner: root
    group: root

# On an add node the password may already be set so ignore errors here
- name: FND-MDB | configure | Set MDB root password
  mysql_user:
    name: root
    password: "{{ mysql_root_pwd }}"
  run_once: true
  ignore_errors: yes

# store root password so the previous task does not fail on subsequent runs
- name: FND-MDB | configure | Store MDB root password
  template:
    src: home/.my.cnf
    dest: ~/
    owner: root
    group: root
    mode: 0600

- name: FND-MDB | configure | Create SST user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pwd }}"
    name: "{{ mysql_sst_user }}"
    password: "{{ mysql_sst_pwd }}"
    host: localhost
    priv: "*.*:RELOAD,LOCK TABLES,REPLICATION CLIENT"
    state: present
  run_once: true

- name: FND-MDB | configure | Create clustercheck user
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_pwd }}"
    name: "{{ mysql_clustercheck_user }}"
    password: "{{ mysql_clustercheck_pwd }}"
    host: 'localhost'
    priv: "*.*:USAGE"
    state: present
  run_once: true

- name: FND-MDB | install | Update services with mysql status service
  lineinfile:
     dest: /etc/services
     state: present
     line: "mysqlchk {{ mysql_clustercheck_port }}/tcp"
     regexp: '^\s*mysqlchk'
  notify: restart xinetd

- name: FND-MDB | configure | configure mysqlchk
  include: configure_mysqlchk.yml

# NOTE direct changes to mysql tables are not replicated.
# However it is safe to run this once here as only the bootstrap
# is up
- name: FND-MDB | start | Delete blank users if mysql up
  command: mysql mysql -e "
    delete from user where User=\"\";
    flush privileges;"
  run_once: true

- name: FND-MDB | start | Update root password for all hosts
  command: mysql mysql -e "
    update mysql.user
       set password=PASSWORD( \"{{ mysql_root_pwd }}\" )
       where User=\"root\";
    flush privileges;"
  no_log: true
  run_once: true

- name: FND-MDB | start | Change password in Debian.cnf
  become: yes
  replace: dest=/etc/mysql/debian.cnf
           regexp='password(.*)'
           replace='password = {{ mysql_root_pwd }}'

- name: FND-MDB | start | Change password for debian-sys-maint
  become: yes
  command: >
    mysql --execute="SET PASSWORD FOR 'debian-sys-maint'@'localhost' = PASSWORD('"{{ mysql_root_pwd }}"');flush privileges;"
  run_once: true
  no_log: true
