#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: monasca-default-alarms | misc_services |
    Alarms for various common services
  monasca_alarm_definition:
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    expression: "{{ item.expression }}"
    keystone_token: "{{ default_notification_result.keystone_token }}"
    match_by: "{{ item.match_by | default(['hostname']) }}"
    monasca_api_url: "{{ default_notification_result.monasca_api_url }}"
    severity: "{{ item.severity | default('LOW') }}"
    alarm_actions:
      - "{{ default_notification_result.notification_method_id }}"
    ok_actions:
      - "{{ default_notification_result.notification_method_id }}"
    undetermined_actions:
      - "{{ default_notification_result.notification_method_id }}"
  run_once: True
  register: monasca_misc_alarms_result
  until: not monasca_misc_alarms_result | failed
  retries: "{{ monasca_client_retries }}"
  delay: "{{ monasca_client_retry_delay }}"
  with_items:
    - name: "MySQL Slow Query Rate"
      description: "Alarms when the slow query rate is high"
      expression: "avg(mysql.performance.slow_queries) > 10 times 3"
    - name: "Apache Status"
      description: "Alarms on failure to reach the Apache status endpoint"
      expression: "apache.status > 0"
      severity: "HIGH"
    - name: "Apache Idle Worker Count"
      description: >
        "Alarms when there are no idle workers in the Apache server"
      expression: "avg(apache.performance.idle_worker_count) < 1 times 3"
      severity: "MEDIUM"
    - name: "NTP Time Sync"
      description: "Alarms when the NTP time offset is high"
      expression: "ntp.offset > 5 or ntp.offset < -5"
    - name: "Certificate Expiration Warning"
      description: >
        Alarms when the certificate for an URL is close to expiring
      expression: >
        MIN(https.cert_expire_days, {{ monasca_cert_check_period }}) <
        {{ monasca_warn_cert_expire_days }}
      match_by: "url"
    - name: "Certificate Expiration Critical"
      description: >
        Alarms when the certificate for an URL is extremely close to expiring
      expression: >
        MIN(https.cert_expire_days, {{ monasca_cert_check_period }}) <
        {{ monasca_critical_cert_expire_days }}
      match_by: "url"
      severity: "HIGH"
