#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
#####  Making Keystone changes to set up ceilometer API endpoint:
### 1. Refer: http://docs.openstack.org/juno/install-guide/install/apt/content/ceilometer-controller-install.html
### Step 5 & 6
#####

- name: ceilometer-post-configure | keystone configuration | Get a domain scoped token
  keystone_v3: >
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    login_username={{ keystone.admin_user }}
    login_password={{ keystone.admin_password }}
    login_user_domain_name={{ keystone.default_domain_name }}
    login_domain_name={{ keystone.default_domain_name }}
    action="token_get"
  run_once: true
  register: domain_scoped_token

- name: ceilometer-post-configure | keystone configuration | Create Admin User
  keystone_v3: >
    user_name=ceilometer
    user_password={{ id_password }}
    user_domain_name="Default"
    login_token={{ domain_scoped_token.result  }}
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    action="create_user"
  register: result_ceilkey
  until : not result_ceilkey|failed
  retries: 6
  delay: 5
  run_once: true

- name: ceilometer-post-configure | keystone configuration | Apply admin Role to admin User
  keystone_v3: >
    user_name=ceilometer
    user_domain_name="Default"
    project_domain_name="Default"
    project_name={{ id_service_tenant }}
    role_name={{ id_admin_role }}
    login_token={{ domain_scoped_token.result  }}
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    action="grant_project_role"
  run_once: true

- name: ceilometer-post-configure | keystone configuration | Search if Reseller admin role exists
  keystone_v3: >
    role_name=ResellerAdmin
    login_token={{ domain_scoped_token.result  }}
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    action="find_role"
  run_once: true
  register: find_role_result

- name: ceilometer-post-configure |Set if Swift is not intalled
  set_fact:
      is_swift_installed: False
  when: not find_role_result.result
  run_once: true

- name: ceilometer-post-configure |Set if Swift is intalled
  set_fact:
      is_swift_installed: True
  when: find_role_result.result
  run_once: true

- name: ceilometer-post-configure | keystone configuration | Apply ResellerAdmin Role to admin User
  keystone_v3: >
    user_name=ceilometer
    user_domain_name="Default"
    project_domain_name="Default"
    project_name={{ id_service_tenant }}
    role_name=ResellerAdmin
    login_token={{ domain_scoped_token.result  }}
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    action="grant_project_role"
  run_once: true
  when: is_swift_installed

- name: ceilometer-post-configure | keystone configuration | Apply monasca-user Role to admin User
  keystone_v3: >
    user_name=ceilometer
    user_domain_name="Default"
    project_domain_name="Default"
    project_name={{ id_service_tenant }}
    role_name=monasca-user
    login_token={{ domain_scoped_token.result  }}
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    action="grant_project_role"
  run_once: true

- name: ceilometer-post-configure | keystone configuration | Create Ceilometer Service
  keystone_v3: >
   endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
   login_token="{{ domain_scoped_token.result  }}"
   service_type="metering"
   service_name="ceilometer"
   description="Ceilometer Service"
   action="create_service"
  run_once: true

- name: ceilometer-post-configure | keystone configuration |  Create Ceilometer Endpoint
  keystone_v3: >
    endpoint="{{ id_admin_uri }}/{{ service_config_keystone_ver }}"
    login_token="{{ domain_scoped_token.result  }}"
    service_name="ceilometer"
    region="{{ cm_region }}"
    admin_url="{{ ceilometer_api_vip_admin_url }}/"
    internal_url="{{ ceilometer_api_vip_private_url }}/"
    public_url="{{ ceilometer_api_vip_public_url }}/"
    action="create_endpoint"
  run_once: true
