#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Defaults
eon_user : eon
eon_group : eon
eon_logs_dir : /var/log/eon
protocol : http
# flag set in configure playbooks to trigger services handlers to restart
eon_restart_required: false

# RabbitMQ
rabbit_userid : "{{ EON.consumes_FND_RMQ.vars.accounts.eon.username }}"
rabbit_password : "{{ EON.consumes_FND_RMQ.vars.accounts.eon.password }}"
_rabbit_hosts_list : "{{ EON_API.consumes_FND_RMQ.members.private }}"
rabbit_hosts: "{% for x in _rabbit_hosts_list %}{{ x.host }}:{{ x.port }}{%if not loop.last %},{% endif %}{% endfor %}"

# Database
esx_sql_connection : "mysql://{{ EON_CND.consumes_FND_MDB.vars.accounts.eon.username }}:{{ EON_CND.consumes_FND_MDB.vars.accounts.eon.password | urlencode }}@{{ EON_CND.consumes_FND_MDB.vips.private[0].host }}/{{ EON_CND.consumes_FND_MDB.vars.databases.eon.dbname }}"

# Auditing
enable_eon_api_auditing: "{{ EON.audit.enabled }}"
eon_api_audit_log_location: "{{ EON.audit.dir }}"
eon_notification_driver: "log"

# Neutron
neutron_admin_auth_url: "{{ EON_API.consumes_KEY_API.vips.private[0].url }}/v3"
neutron_admin_tenant_name: "{{ KEY_API.vars.keystone_service_tenant }}"
neutron_admin_password: "{{ NEU_SVR.consumes_KEY_API.vars.keystone_neutron_password | quote }}"
neutron_admin_username: "{{ NEU_SVR.consumes_KEY_API.vars.keystone_neutron_user }}"
neutron_url: "{{ NEU_SVR.advertises.vips.private[0].url }}"
neutron_endpoint_type: "internalURL"

# Keystone
eon_admin_tenant_name : "{{ KEY_API.vars.keystone_service_tenant }}"
eon_admin_password : "{{ EON_API.consumes_KEY_API.vars.keystone_eon_password | quote }}"
eon_admin_user : "{{ EON_API.consumes_KEY_API.vars.keystone_eon_user }}"
keystone_auth_uri: "{{ EON_API.consumes_KEY_API.vips.private[0].url }}"
keystone_identity_uri: "{{ EON_API.consumes_KEY_API.vips.private[0].url }}"

# eon api
host_ip : "{% if host.bind.EON_API is defined %}{{ host.bind.EON_API.admin.ip_address }}{% endif %}"
port : "{% if host.bind.EON_API is defined %}{{ host.bind.EON_API.admin.port }}{% endif %}"
