#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: rabbitmq-monasca | configure | Setup Monasca with RabbitMQ mgmt
  become: yes
  no_log: true
  monasca_agent_plugin:
    name: rabbitmq
    args: >
      watch_api=True
      api_url={{ rabbitmq_monasca_cp.monasca_api_url }}
      user={{ rabbitmq_monasca_cp.monasca_username }}
      password={{ rabbitmq_monasca_cp.monasca_password | quote }}
  when: ("rabbitmq_management" in rabbitmq_plugins)

# This task is taking care of the upgrade path or any other time the rabbitmq
# plugin is not configured. This is because when the plugin is not configured
# we should have no rabbitmq.yaml file and just have the process checks in the
# process.yaml so this makes sure in that case that there is no rabbitmq.yaml
# file that would give our agent problems. On upgrade since we are going from
# it being enabled to not this will handle that as well as it is removing the
# rabbitmq.yaml config.
- name: rabbitmq-monasca | configure | Remove outdated Monasca RabbitMQ config
  become: yes
  file:
    path: /etc/monasca/agent/conf.d/rabbitmq.yaml
    state: absent
  when: ("rabbitmq_management" not in rabbitmq_plugins)

- name: rabbitmq-monasca | configure | Setup Monasca without RabbitMQ mgmt
  become: yes
  monasca_agent_plugin:
    name: rabbitmq
    args: >
      watch_api=False
  when: ("rabbitmq_management" not in rabbitmq_plugins)
