#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This file will contain the default values for the nova-api service
---
nova_component: nova-api

# the filters nova-common will copy for this service
nova_rootwrap_filters:
  - rootwrap.d/api-metadata.filters

# the policy file nova-common will copy for this service
nova_policy_file: ../../nova-common/templates/policy.json.j2

nova_api_etc_dir: "{{ nova_component | config_dir() }}"
nova_api_conf_dir: "{{ nova_component | config_dir() }}/nova"
nova_api_bin_dir: "{{ nova_component | bin_dir() }}"
