#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
sub_service:
  name: deployer
  service: deployer
  logging_options:
    - centralized_logging:
        enabled: false
        format: json
      files:
      - /var/log/configuration_processor/errors.log
      log_rotate:
      - weekly
      - compress
      - missingok
      - notifempty
      - copytruncate
      - rotate 5
      - maxsize 45M
      - delaycompress
      - create 755 stack stack
    - centralized_logging:
        enabled: false
        format: json
      files:
      - /var/log/lastlog
      log_rotate:
      - weekly
      - compress
      - missingok
      - notifempty
      - copytruncate
      - rotate 5
      - maxsize 45M
      - delaycompress
      - create 664 root utmp
    - centralized_logging:
        enabled: false
        format: json
      files:
      - /var/log/faillog
      - /var/log/fontconfig.log
      - /var/log/cobbler/tasks/*.log
      - /var/log/cobbler/cobbler.log
      log_rotate:
      - weekly
      - compress
      - missingok
      - notifempty
      - copytruncate
      - rotate 5
      - maxsize 45M
      - delaycompress
      - create 644 root root
    - centralized_logging:
        enabled: false
        format: json
      files:
      - /var/log/configuration_processor/output.log
      log_rotate:
      - weekly
      - compress
      - missingok
      - notifempty
      - copytruncate
      - rotate 5
      - maxsize 45M
      - delaycompress
      - create 644 stack stack
    - centralized_logging:
        enabled: false
        format: json
      files:
      - /var/log/dmesg
      - /var/log/fsck/checkfs
      - /var/log/fsck/checkroot
      log_rotate:
      - weekly
      - compress
      - missingok
      - notifempty
      - copytruncate
      - rotate 5
      - maxsize 45M
      - delaycompress
      - create 644 root adm
