#
# (c) Copyright 2015,2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Remove old Directory Detect Plugin files for 2.X to 3.0 upgrade only
#------------------------------------------------------------------------------
- name: logging-monitor | configure | Directory Detect plugin files removal
  file: state=absent path={{ item }}
  register: hlm_notify_monitor_directory_restart
  with_items:
    - /usr/lib/monasca/agent/custom_detect.d/DirectoryDetect.pyc
    - /usr/lib/monasca/agent/custom_detect.d/DirectoryDetect.py
    - /etc/monasca/agent/conf.d/directory.yaml

# Configure Monasca detection plugins for SVR hosts
#------------------------------------------------------------------------------
- name: logging-monitor | configure | Apache detection plugin directory creation
  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
  register: hlm_notify_monitor_apache_restart

- name: logging-monitor | configure | Apache detection plugin file copy
  copy: src=ApacheDetect.py dest=/usr/lib/monasca/agent/custom_detect.d/ApacheDetect.py owner=root group=root mode=0644
  register: hlm_notify_monitor_apache_restart

- name: logging-monitor | configure | Beaver detection plugin directory creation
  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
  register: hlm_notify_monitor_beaver_restart

- name: logging-monitor | configure | Beaver detection plugin file copy
  copy: src=BeaverDetect.py dest=/usr/lib/monasca/agent/custom_detect.d/ owner=root group=root mode=0644
  register: hlm_notify_monitor_beaver_restart

- name: logging-monitor | configure | Elasticsearch detection plugin directory creation
  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
  register: hlm_notify_monitor_elasticsearch_restart

- name: logging-monitor | configure | Elasticsearch detection plugin file copy
  template: src=ElasticDetect.py.j2 dest=/usr/lib/monasca/agent/custom_detect.d/ElasticDetect.py owner=root group=root mode=0644
  register: hlm_notify_monitor_elasticsearch_restart

- name: logging-monitor | configure | Directory detection logging plugin directory creation
  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
  register: hlm_notify_monitor_directory_restart

- name: logging-monitor | configure | Directory detection logging plugin file copy
  template: src=DirectoryDetectLogging.py.j2 dest=/usr/lib/monasca/agent/custom_detect.d/DirectoryDetectLogging.py owner=root group=root mode=0644
  register: hlm_notify_monitor_directory_restart

- name: logging-monitor | configure | Kibana detection plugin directory creation
  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
  register: hlm_notify_monitor_kibana_restart

- name: logging-monitor | configure | Kibana detection plugin file copy
  copy: src=KibanaDetect.py dest=/usr/lib/monasca/agent/custom_detect.d/ owner=root group=root mode=0644
  register: hlm_notify_monitor_kibana_restart

- name: logging-monitor | configure | Logstash detection plugin directory creation
  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
  register: hlm_notify_monitor_logstash_restart

- name: logging-monitor | configure | Logstash detection plugin file copy
  copy: src=LogstashDetect.py dest=/usr/lib/monasca/agent/custom_detect.d/ owner=root group=root mode=0644
  register: hlm_notify_monitor_logstash_restart

# NOTE - this is currently a work in progress to monitor the size of individual log files.
#- name: logging-monitor | configure | File Size plugin directory creation
#  file: path=/usr/lib/monasca/agent/custom_detect.d state=directory owner=root group=root mode=0755
#  register: hlm_notify_monitor_filesize_restart
#
#- name: logging-monitor | configure | File Size plugin file copy
#  template: src=FileSize.py.j2 dest=/usr/lib/monasca/agent/custom_detect.d/FileSize.py owner=root group=root mode=0644
#  register: hlm_notify_monitor_filesize_restart
